### ISSUE TITLE
Dead link in Readme.md

### ISSUE THREAD

**Issue by btreut** [markush81/JGR#2]
Hi Markus,

this is just to let you know that the link in Readme.md pointing to the "Statistical Computing and Graphics Newsletter Vol 16 nr 2 p9-12" is dead. It should apparently be adjusted to point to http://stat-computing.org/newsletter/issues/scgn-16-2.pdf instead of http://stat-computing.org/newsletter/v162.pdf

regards
--
  Bernhard

**Comment by markush81** [comment]
thanks, fixed now.
