### ISSUE TITLE
JGR showing splash screen and the nonresposeable console than crashes

### ISSUE THREAD

**Issue by AlekseyBuzmakov** [markush81/JGR#4]
Xubuntu 16.04. openjdk 6&7

installing openjdk
running R CMD javareconf
running R -> instal.packages("JGR") -> library("JGR") -> JGR()
The splash screen is shown and irresposible JGR console. Then after a while a crash with segmentation fault in Rinit_with_padding.

Tried in two computers other one is 32bit Xubuntu 14.04. The same result.

**Comment by rbdekock** [comment]
Same problem only with openjdk 8

**Comment by MarkusLoew** [comment]
Happens on my systems (Ubuntu 16.04 and 17.10, JDK 8) as well since rJava published rJava 0.9-9. 
"java crashed with SIGSEGV in RinitJVM_with_padding()" when starting JGR()
Downgrading rJava back to version rJava_0.9-8 solves the issue. Could be a bug in rJava 0.9-9 that causes the crash?
