### ISSUE TITLE
com.apple.eawt.Application.setAboutHandler

### ISSUE THREAD

**Issue by tvschuer** [markush81/JGR#6]
Hi

I'm having a hard time getting JGR running ons osx 10.13.6.
java version "9.0.1", rJava installed

But when I run JGR, I keep ending up with this stacktrace:
```
ERROR: while running main method: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at RJavaClassLoader.bootClass(RJavaClassLoader.java:532)
at RJavaClassLoader.main(RJavaClassLoader.java:602)
Caused by: java.lang.NoSuchMethodError: com.apple.eawt.Application.setAboutHandler(Lcom/apple/eawt/AboutHandler;)V
at org.rosuda.JGR.JGR.main(JGR.java:570)
... 6 more
```

I've tried reinstalling java, without success. Is there a specific osx java version I should be installing?

**Comment by markush81** [comment]
i guess this is an issue of JDK 9 Jigsaw modularisation. I have to check how to solve this.

**Comment by kirstenez** [comment]
I am having this same problem and error message when tying to run JGR on mac, but JDK 1.8.x is no longer available. I am using JDK 11.

**Comment by nwijermans** [comment]
Having the same issue JDK 11.0.1. Has anyone found a solution for this already?

**Comment by markush81** [comment]
> Having the same issue with JDK 11.0.1. Has anyone found a solution for this already?

there is a solution in a branch ... last time i added to master, there where complaints since R itself was/is still Java 8 based.

**Comment by nwijermans** [comment]
Good to know there is a solution. How would I find this? I looked into the master but couldn't find it.
It seems that JGR wants Java 8, however I updated to Java 11 to make JavaGD and rJava work...
Could you guide me to the right solution message?

**Comment by markush81** [comment]
> Good to know there is a solution. How would I find this? I looked into the master but couldn't find it.
> It seems that JGR wants Java 8, however I updated to Java 11 to make JavaGD and rJava work...
> Could you guide me to the right solution message?

i will build a tgz tomorrow and add it as github release. Which OS are you using?

**Comment by nwijermans** [comment]
Thanks! Using OS 10.15.4.

**Comment by markush81** [comment]
> Thanks! Using OS 10.15.4.

Please try following

```
install.packages('JGR')
install.packages('https://github.com/markush81/JGR/releases/download/1.9-0/JGR_1.9.0.tar.gz',repos=NULL)
```

First line to get dependent packages
Second to get JGR with changes needed for JDK > 1.9.x

But i guess the problem will stay since dependent packages are not ready for Java > 1.8.x

**Comment by nwijermans** [comment]
This does the trick! Thanks so much for your swift action, very much appreciated!

/Nanda

**Comment by lshifr** [comment]
@markush81 Amazing! Thanks a lot! Much appreciated.

**Comment by AMALCGCG** [comment]
@markush81 This works for me as well (thank you!). But I can't seem to get it to work in my renv.lock file. The following doesn't seem to work:

"JGR": {
  "Package": "JGR",
  "Version": "1.91",
  "Source": "https://github.com/markush81/JGR/releases/download/1.9-1/JGR_1.9-1.tar.gz"
}

Do you have any suggestions? Thanks in advance.

**Comment by markush81** [comment]
> renv.lock

i have no experiance with renv, but it seems thet `"Version"` might be wrong, cause it is `1.91` vs. real `1.9-1`?

**Comment by AMALCGCG** [comment]
@markush81 Thank you for the fast reply. I changed the version to match, but no luck. More detail below.

```
"JGR": {
  "Package": "JGR",
  "Version": "1.9-1",
  "Source": "https://github.com/markush81/JGR/releases/download/1.9-1/JGR_1.9-1.tar.gz"
},
```

In the renv::restore() command and output below, it looks like it's still trying to pull from the wrong location (cloud.r-project.org). It's likely this is a question for the renv maintainer. (Btw, we're using renv so we can have reproducible environments across the team.)

Do you know when you might be publishing these new versions to CRAN? It would make great to be able to treat this as a regular dependency.

```
> renv::restore()
The following package(s) will be updated:

# CRAN ===============================
- JavaGD   [* -> 0.6-1.1]
- rJava    [* -> 0.9-12]

# https://github.com/markush81/JGR/releases/download/1.9-1/JGR_1.9-1.tar.gz
- JGR      [* -> 1.9-1]

Do you want to proceed? [y/N]: y
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
Retrieving 'https://cloud.r-project.org/src/contrib/Archive/JGR/JGR_1.9-1.tar.gz' ...
Error: failed to retrieve package 'JGR'
```

**Comment by markush81** [comment]
guess, this really is a renv issue, fetching from wrong location.

about CRAN i have no clue yet, since most java packages at CRAN are AFAIK still built against Java 1.8.x i still suspect this to be the default.
